username: 'BhargavBanoth7'
password: 'KingofTraders@07'
cookie: '_gh_sess=5RUrzoJ7iSMDPSoEqsrpHAnGMPlvNhi305bKDqFpfZsFx2wyU22W%2BLF7C5muDqDcOF0s4CTMQz%2Fh1ToMt1DB7JlfNxBecD7a6dUAR6dalF6uiw3fhqBS1CGa6gA55dhuj5y392%2BpXav4sdVsDLR4nOOt08i9crOFHi%2BOQlR7HyNZRDxY5fY4oGNMg%2BgBqnaNKN6V90nVwY8MLCRTSMiCaPS%2BGIFqq3hMLrrtBKjAZatuvR8McwhVW8qRTWAq4y1GaVG570ROhDCTi5988lkcxw%3D%3D--Jm%2F57uHJmqQaPWz4--hAdSC%2FaCMgezj%2BAgN1YI3w%3D%3D; _octo=GH1.1.424705881.1714188042; logged_in=no'
